/**
 * End-to-end encryption for anything that crosses the relay.
 *
 * The key is generated by the Storyteller's device and travels only inside the
 * QR fragment, which is never sent to any server. The relay therefore moves
 * opaque bytes and cannot see a role, a name or a script even in principle.
 * That is worth the roughly thirty lines it costs: it removes the entire
 * question of what the server knows.
 */

const ALGORITHM = 'AES-GCM'
const KEY_BYTES = 16
const IV_BYTES = 12

export function generateKeyMaterial(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(KEY_BYTES))
}

export async function importKey(material: Uint8Array): Promise<CryptoKey> {
  return crypto.subtle.importKey('raw', material, ALGORITHM, false, ['encrypt', 'decrypt'])
}

export async function encryptJson(key: CryptoKey, value: unknown): Promise<Uint8Array> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES))
  const plaintext = new TextEncoder().encode(JSON.stringify(value))
  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt({ name: ALGORITHM, iv }, key, plaintext),
  )
  const out = new Uint8Array(iv.length + ciphertext.length)
  out.set(iv, 0)
  out.set(ciphertext, iv.length)
  return out
}

export async function decryptJson<T>(key: CryptoKey, bytes: Uint8Array): Promise<T> {
  const iv = bytes.slice(0, IV_BYTES)
  const ciphertext = bytes.slice(IV_BYTES)
  const plaintext = await crypto.subtle.decrypt({ name: ALGORITHM, iv }, key, ciphertext)
  return JSON.parse(new TextDecoder().decode(plaintext)) as T
}

/** A short, unguessable room id. */
export function generateRoomId(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(6))
  return Array.from(bytes, (b) => b.toString(36).padStart(2, '0')).join('').slice(0, 8)
}
